[versions]
java = "17"
kotlin = "2.4.10"
coroutines = "1.11.0"
ktor = "3.5.2"
nimbus-sdk = "11.38.2"
fasterxml-jackson = "2.18.2"
bouncyCastle = "1.83"
spotless = "7.0.2"
ktlint = "0.50.0"
dokka = "2.2.0"
maven-publish = "0.35.0"
kover = "0.9.9"
dependency-check = "12.2.0"
tink = "1.21.0"
logback = "1.5.32"
kotlinx-datetime = "0.8.0-0.6.x-compat"
cose-java = "1.1.0"
waltid-mdoc-credentials = "0.11.0"
kotlinx-serialization = "1.11.0"

[libraries]
fasterxml-jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "fasterxml-jackson" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
nimbus-oauth2-oidc-sdk = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "nimbus-sdk" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
bouncy-castle = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncyCastle" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
cose-java = { module = "com.augustcellars.cose:cose-java", version.ref = "cose-java" }
waltid-mdoc-credentials = { module = "id.walt.mdoc-credentials:waltid-mdoc-credentials", version.ref = "waltid-mdoc-credentials" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
dependency-check = { id = "org.owasp.dependencycheck", version.ref = "dependency-check" }