name: Build Verifier project
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

permissions:
  contents: read
  packages: read

jobs:
  build-gradle:
    # Run on external PRs, but not on internal PRs since those will be run by push to branch
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        env:
          GH_PKG_USER: ${{ github.actor }}
          GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }}
          DEP_MVN_REPO: https://maven.pkg.github.com/${{ github.repository_owner }}/*
        with:
          arguments: build

