name: Build Verifier project

on:
  push:

permissions:
  contents: read
  packages: read

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        env:
          GH_PKG_USER: ${{ github.actor }}
          GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }} # This is a personal token, defined as secret to allow downloading
                                                    # dependencies from GitÎ—ub Packages
        with:
          arguments: build

