name: SonarCloud
on:
  push:
    branches: [ 'main' ]
    tags: [ v* ]
    paths:
      # SonarQube's analysis will only be triggered when there are changes under /src folder
      - src/**

jobs:
  run-sast:
    name: Build and run SonarQube analysis
    # Run on external PRs, but not on internal PRs since those will be run by push to branch
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle Wrapper & Run Sonar
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build sonar --info --full-stacktrace -Dsonar.organization=niscy-eudiw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          CI: true